# Docker Compose configuration for AION License Count application

version: '3.8'

services:
  # Web service configuration
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SHAREPOINT_SITE: aionpartners.sharepoint.com
      SHAREPOINT_DRIVE_ID: 68757f86-5521-4e8f-a50d-d61f3bbba0ec
      SHAREPOINT_FOLDER: "Onboarding Form"
      SHAREPOINT_CLIENT_ID: 9bf132e8-4d54-46d8-b611-f85185a98cfe
      SHAREPOINT_CLIENT_SECRET: 
      SHAREPOINT_TENANT_ID: 531ad474-be34-4584-a4bf-c885279053f5
    volumes:
      - .:/app
      - /app/node_modules
      - ./results:/app/results
      - /etc/letsencrypt/live/onboarding.aiontechnology.org/privkey.pem:/etc/letsencrypt/live/onboarding.aiontechnology.org/privkey.pem:ro
      - /etc/letsencrypt/live/onboarding.aiontechnology.org/fullchain.pem:/etc/letsencrypt/live/onboarding.aiontechnology.org/fullchain.pem:ro
    ports:
      - "3001:3001"
    restart: always
    labels:
      io.portainer.accesscontrol.users: regularuser
