# Docker Compose configuration for AION License Count application

version: '3.8'

services:
  # Web service configuration
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
      - /app/node_modules
      - ./results:/app/results
      - /etc/letsencrypt/live/onboarding.aiontechnology.org/privkey.pem:/etc/letsencrypt/live/onboarding.aiontechnology.org/privkey.pem:ro
      - /etc/letsencrypt/live/onboarding.aiontechnology.org/fullchain.pem:/etc/letsencrypt/live/onboarding.aiontechnology.org/fullchain.pem:ro
    ports:
      - "3001:3001"
    restart: always
