# Docker Compose configuration for AION License Count application

version: '3.8'

services:
  # Web service configuration
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
      - /app/node_modules
      - ./results:/app/results
    ports:
      - "3001:3001"
    restart: always
